# -*- coding: utf-8 -*-
from __future__ import annotations

import base64
import hashlib
import json
import os
import subprocess
import sys
import zlib
from pathlib import Path

ROOT = Path(__file__).resolve().parent
PAYLOAD = ROOT / "stage4_v4_1_1.py.zlib.b64"
MONITOR = ROOT / "04_SHADOW_FORWARD_MONITOR.py"
UNIVERSE = ROOT / "frozen_universe.json"
MODEL = ROOT / "reports" / "stage2" / "regime_model.json"
SITEPATCH = ROOT / "sitecustomize.py"
EXPECTED_SHA256 = "45fbce1e258c387eff246fe42202a6e02e22bf71983dc0f9089ee5138b33c4b1"


def ensure_monitor() -> None:
    raw = zlib.decompress(base64.b64decode("".join(PAYLOAD.read_text(encoding="utf-8").split())))
    digest = hashlib.sha256(raw).hexdigest()
    if digest != EXPECTED_SHA256:
        raise SystemExit(f"Stage4 payload SHA256 uyuşmuyor: {digest}")
    if not MONITOR.exists() or hashlib.sha256(MONITOR.read_bytes()).hexdigest() != EXPECTED_SHA256:
        MONITOR.write_bytes(raw)


def ensure_frozen_universe() -> int:
    obj = json.loads(UNIVERSE.read_text(encoding="utf-8"))
    symbols = obj.get("symbols", [])
    if len(symbols) != 401:
        raise SystemExit(f"Frozen universe 401 sembol olmalı; bulundu={len(symbols)}")
    d = ROOT / "data" / "discovery_events"
    d.mkdir(parents=True, exist_ok=True)
    for old in d.glob("*.parquet"):
        old.unlink()
    for symbol in symbols:
        (d / f"{symbol}.parquet").touch()
    return len(symbols)


def install_binance_public_failover() -> None:
    """GitHub-hosted runnerlarda api.binance.com 451 dönebildiği için yalnız ağ katmanını yönlendirir.

    Stage4 araştırma/sinyal kurallarına dokunmaz. Monitor yine aynı /api/v3 public endpointlerini
    çağırır; requests katmanı aynı Binance public verisini alternatif resmi hostlardan alır.
    """
    SITEPATCH.write_text(
        r'''# Auto-generated by run_stage4_github.py -- network transport only.
import requests

_ORIGINAL_REQUEST = requests.sessions.Session.request
_BINANCE_HOSTS = (
    "https://data-api.binance.vision",
    "https://api-gcp.binance.com",
    "https://api1.binance.com",
    "https://api2.binance.com",
    "https://api3.binance.com",
)


def _request_with_binance_failover(self, method, url, *args, **kwargs):
    if isinstance(url, str) and url.startswith("https://api.binance.com"):
        suffix = url[len("https://api.binance.com"):]
        last_response = None
        last_error = None
        for base in _BINANCE_HOSTS:
            try:
                response = _ORIGINAL_REQUEST(self, method, base + suffix, *args, **kwargs)
                last_response = response
                if response.status_code not in (418, 429, 451) and response.status_code < 500:
                    return response
            except requests.RequestException as exc:
                last_error = exc
        if last_response is not None:
            return last_response
        if last_error is not None:
            raise last_error
    return _ORIGINAL_REQUEST(self, method, url, *args, **kwargs)


requests.sessions.Session.request = _request_with_binance_failover
''',
        encoding="utf-8",
    )


def main() -> None:
    ensure_monitor()
    n = ensure_frozen_universe()
    if not MODEL.exists():
        raise SystemExit(
            "Eksik frozen bağımlılık: reports/stage2/regime_model.json. "
            "Stage 2'de kullanılan dosyanın aynısı gerekir; yeniden fit edilmeyecek."
        )
    install_binance_public_failover()
    print(f"[DEPLOY] exact Stage4 v4.1.1 sha256={EXPECTED_SHA256[:16]}…")
    print(f"[DEPLOY] frozen universe={n}")
    print("[DEPLOY] Binance public API transport failover=enabled")
    env = os.environ.copy()
    old_pythonpath = env.get("PYTHONPATH", "")
    env["PYTHONPATH"] = str(ROOT) + (os.pathsep + old_pythonpath if old_pythonpath else "")
    subprocess.run(
        [sys.executable, str(MONITOR), "--once", "--workers", "5"],
        cwd=str(ROOT),
        env=env,
        check=True,
    )


if __name__ == "__main__":
    main()
